export default {
   content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
   plugins: [require('@tailwindcss/typography')],
   theme: {
      extend: {
         colors: {
            background: 'var(--background)',
            foreground: 'var(--foreground)',
            card: 'var(--card)',
            'card-foreground': 'var(--card-foreground)',
            popover: 'var(--popover)',
            'popover-foreground': 'var(--popover-foreground)',
            primary: {
               DEFAULT: 'var(--primary)',
               foreground: 'var(--primary-foreground)',
            },
            secondary: {
               DEFAULT: 'var(--secondary)',
               foreground: 'var(--secondary-foreground)',
            },
            muted: {
               DEFAULT: 'var(--muted)',
               foreground: 'var(--muted-foreground)',
            },
            accent: {
               DEFAULT: 'var(--accent)',
               foreground: 'var(--accent-foreground)',
            },
            destructive: {
               DEFAULT: 'var(--destructive)',
               foreground: 'var(--destructive-foreground)',
            },
            border: 'var(--border)',
            input: 'var(--input)',
            ring: 'var(--ring)',
            'input-background': 'var(--input-background)',
            'switch-background': 'var(--switch-background)',
            tertiary: 'var(--text-tertiary)',
            'text-primary': 'var(--text-primary)',
            'text-secondary': 'var(--text-secondary)',
            'line-subtle': 'var(--line-subtle)',
            'line-strong': 'var(--line-strong)',
            sidebar: 'var(--sidebar)',
            'sidebar-foreground': 'var(--sidebar-foreground)',
            'sidebar-primary': 'var(--sidebar-primary)',
            'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
            'sidebar-accent': 'var(--sidebar-accent)',
            'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
            'sidebar-border': 'var(--sidebar-border)',
            'sidebar-ring': 'var(--sidebar-ring)',
            'chart-1': 'var(--chart-1)',
            'chart-2': 'var(--chart-2)',
            'chart-3': 'var(--chart-3)',
            'chart-4': 'var(--chart-4)',
            'chart-5': 'var(--chart-5)',
         },
         borderRadius: {
            sm: 'calc(var(--radius) - 4px)',
            md: 'calc(var(--radius) - 2px)',
            lg: 'var(--radius)',
            xl: 'calc(var(--radius) + 4px)',
         },
      },
   },
};
